{
 "title": "BackgroundScavengers",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Scavengers running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum without (instance, pod) (started)) - (sum without (instance, pod) (stopped or started*0))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "DBRequestsRate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate (scavenger_db_requests[5m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "ExecutionsPerShard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executions_scavenger_executions_count"
    },
    {
     "expr": "executions_scavenger_corrupted_executions_count"
    }
   ]
  },
  {
   "title": "ExecutionsLeftToScan",
   "type": "graph",
   "description": "Might stuck until scavenger rerun in case of worker crash.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pod)(executions_outstanding)"
    }
   ]
  },
  {
   "title": "DetailedErrors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(scavenger_validation_failures[5m]))",
     "legendFormat": "{{cluster}} - {{validator}} - {{failure}}"
    }
   ]
  }
 ]
}